import { expect, test } from "@playwright/test";

// source-intent: e2e/intents/auth/login.intent.md
// Generated by: agy -p "Read e2e/intents/auth/login.intent.md and create this
// spec using getByRole/getByLabel. Run it until it passes. Do not change app code."
//
// Compare with docs/examples/brittle-login.spec.ts.example: same journey, no
// CSS classes. This version keeps passing after `make break-ui`.
test("host can sign in and reach the wallet overview", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("link", { name: /^sign in$/i }).first().click();

  await page.getByLabel("Email").fill(process.env.TEST_HOST_EMAIL ?? "host@bookmi.test");
  await page
    .getByLabel("Password", { exact: true })
    .fill(process.env.TEST_HOST_PASSWORD ?? "password");
  await page.getByRole("button", { name: /^(sign in|log in)$/i }).click();

  await expect(page.getByRole("heading", { name: "Wallet overview" })).toBeVisible();
  await expect(page.getByText("Wallet balance")).toBeVisible();
});

test("wrong password is rejected", async ({ page }) => {
  await page.goto("/auth/login");

  await page.getByLabel("Email").fill("host@bookmi.test");
  await page.getByLabel("Password", { exact: true }).fill("not-the-password");
  await page.getByRole("button", { name: /^(sign in|log in)$/i }).click();

  await expect(page.getByText("Invalid email or password")).toBeVisible();
});
